ALTER TABLE tpopkontr DROP INDEX TPopKontrZaehleinheit1;
ALTER TABLE tpopkontr DROP INDEX TPopKontrMethode1;
ALTER TABLE tpopkontr DROP INDEX TPopKontrZaehleinheit2;
ALTER TABLE tpopkontr DROP INDEX TPopKontrMethode2;
ALTER TABLE tpopkontr DROP INDEX TPopKontrZaehleinheit3;
ALTER TABLE tpopkontr DROP INDEX TPopKontrMethode3;
ALTER TABLE tpopkontr DROP TPopKontrZaehleinheit1;
ALTER TABLE tpopkontr DROP TPopKontrMethode1;
ALTER TABLE tpopkontr DROP TPopKontrAnz1;
ALTER TABLE tpopkontr DROP TPopKontrZaehleinheit2;
ALTER TABLE tpopkontr DROP TPopKontrMethode2;
ALTER TABLE tpopkontr DROP TPopKontrAnz2;
ALTER TABLE tpopkontr DROP TPopKontrZaehleinheit3;
ALTER TABLE tpopkontr DROP TPopKontrMethode3;
ALTER TABLE tpopkontr DROP TPopKontrAnz3;