CREATE TABLE IF NOT EXISTS evab_tbl_personen (
idPerson VARCHAR(40) NOT NULL PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Vorname VARCHAR(50) NOT NULL,
Ort VARCHAR(50) NOT NULL) ENGINE=INNODB COMMENT="tblPersonen aus Evab";