/*
 * diese Views hängen von anderen ab, die in viewsGenerieren2.sql erstellt werden
 * daher muss dieser code NACH viewsGenerieren2.sql ausgeführt werden
 */

DROP VIEW IF EXISTS views.v_tpop_anzkontrinklletzterundletztertpopber CASCADE;
CREATE OR REPLACE VIEW views.v_tpop_anzkontrinklletzterundletztertpopber AS
SELECT
	views.v_tpop_anzkontrinklletzter."ApArtId" AS "ApArtId",
	views.v_tpop_anzkontrinklletzter."Familie",
	views.v_tpop_anzkontrinklletzter."AP Art",
	views.v_tpop_anzkontrinklletzter."AP Status",
	views.v_tpop_anzkontrinklletzter."AP Start im Jahr",
	views.v_tpop_anzkontrinklletzter."AP Stand Umsetzung",
	views.v_tpop_anzkontrinklletzter."AP verantwortlich",
	views.v_tpop_anzkontrinklletzter."Pop Guid",
	views.v_tpop_anzkontrinklletzter."Pop Nr",
	views.v_tpop_anzkontrinklletzter."Pop Name",
	views.v_tpop_anzkontrinklletzter."Pop Status",
	views.v_tpop_anzkontrinklletzter."Pop bekannt seit",
	views.v_tpop_anzkontrinklletzter."TPop ID",
	views.v_tpop_anzkontrinklletzter."TPop Guid",
	views.v_tpop_anzkontrinklletzter."TPop Nr",
	views.v_tpop_anzkontrinklletzter."TPop Gemeinde",
	views.v_tpop_anzkontrinklletzter."TPop Flurname",
	views.v_tpop_anzkontrinklletzter."TPop Status",
	views.v_tpop_anzkontrinklletzter."TPop bekannt seit",
	views.v_tpop_anzkontrinklletzter."TPop Status unklar",
	views.v_tpop_anzkontrinklletzter."TPop Begruendung fuer unklaren Status",
	views.v_tpop_anzkontrinklletzter."TPop X-Koordinaten",
	views.v_tpop_anzkontrinklletzter."TPop Y-Koordinaten",
	views.v_tpop_anzkontrinklletzter."TPop Radius (m)",
	views.v_tpop_anzkontrinklletzter."TPop Hoehe",
	views.v_tpop_anzkontrinklletzter."TPop Exposition",
	views.v_tpop_anzkontrinklletzter."TPop Klima",
	views.v_tpop_anzkontrinklletzter."TPop Hangneigung",
	views.v_tpop_anzkontrinklletzter."TPop Beschreibung",
	views.v_tpop_anzkontrinklletzter."TPop Kataster-Nr",
	views.v_tpop_anzkontrinklletzter."TPop fuer AP-Bericht relevant",
	views.v_tpop_anzkontrinklletzter."TPop EigentuemerIn",
	views.v_tpop_anzkontrinklletzter."TPop Kontakt vor Ort",
	views.v_tpop_anzkontrinklletzter."TPop Nutzungszone",
	views.v_tpop_anzkontrinklletzter."TPop BewirtschafterIn",
	views.v_tpop_anzkontrinklletzter."TPop Bewirtschaftung",
	views.v_tpop_anzkontrinklletzter."TPop Anzahl Kontrollen",
	views.v_tpop_anzkontrinklletzter."TPopKontrId",
	views.v_tpop_anzkontrinklletzter."TPopId",
	views.v_tpop_anzkontrinklletzter."Kontr Guid",
	views.v_tpop_anzkontrinklletzter."Kontr Jahr",
	views.v_tpop_anzkontrinklletzter."Kontr Datum",
	views.v_tpop_anzkontrinklletzter."Kontr Typ",
	views.v_tpop_anzkontrinklletzter."Kontr BearbeiterIn",
	views.v_tpop_anzkontrinklletzter."Kontr Ueberlebensrate",
	views.v_tpop_anzkontrinklletzter."Kontr Vitalitaet",
	views.v_tpop_anzkontrinklletzter."Kontr Entwicklung",
	views.v_tpop_anzkontrinklletzter."Kontr Ursachen",
	views.v_tpop_anzkontrinklletzter."Kontr Erfolgsbeurteilung",
	views.v_tpop_anzkontrinklletzter."Kontr Aenderungs-Vorschlaege Umsetzung",
	views.v_tpop_anzkontrinklletzter."Kontr Aenderungs-Vorschlaege Kontrolle",
	views.v_tpop_anzkontrinklletzter."Kontr X-Koord",
	views.v_tpop_anzkontrinklletzter."Kontr Y-Koord",
	views.v_tpop_anzkontrinklletzter."Kontr Bemerkungen",
	views.v_tpop_anzkontrinklletzter."Kontr Lebensraum Delarze",
	views.v_tpop_anzkontrinklletzter."Kontr angrenzender Lebensraum Delarze",
	views.v_tpop_anzkontrinklletzter."Kontr Vegetationstyp",
	views.v_tpop_anzkontrinklletzter."Kontr Konkurrenz",
	views.v_tpop_anzkontrinklletzter."Kontr Moosschicht",
	views.v_tpop_anzkontrinklletzter."Kontr Krautschicht",
	views.v_tpop_anzkontrinklletzter."Kontr Strauchschicht",
	views.v_tpop_anzkontrinklletzter."Kontr Baumschicht",
	views.v_tpop_anzkontrinklletzter."Kontr Bodentyp",
	views.v_tpop_anzkontrinklletzter."Kontr Boden Kalkgehalt",
	views.v_tpop_anzkontrinklletzter."Kontr Boden Durchlaessigkeit",
	views.v_tpop_anzkontrinklletzter."Kontr Boden Humusgehalt",
	views.v_tpop_anzkontrinklletzter."Kontr Boden Naehrstoffgehalt",
	views.v_tpop_anzkontrinklletzter."Kontr Oberbodenabtrag",
	views.v_tpop_anzkontrinklletzter."Kontr Wasserhaushalt",
	views.v_tpop_anzkontrinklletzter."Kontr Uebereinstimmung mit Idealbiotop",
	views.v_tpop_anzkontrinklletzter."Kontr Handlungsbedarf",
	views.v_tpop_anzkontrinklletzter."Kontr Ueberpruefte Flaeche",
	views.v_tpop_anzkontrinklletzter."Kontr Flaeche der Teilpopulation m2",
	views.v_tpop_anzkontrinklletzter."Kontr auf Plan eingezeichnet",
	views.v_tpop_anzkontrinklletzter."Kontr Deckung durch Vegetation",
	views.v_tpop_anzkontrinklletzter."Kontr Deckung nackter Boden",
	views.v_tpop_anzkontrinklletzter."Kontr Deckung durch ueberpruefte Art",
	views.v_tpop_anzkontrinklletzter."Kontr auch junge Pflanzen",
	views.v_tpop_anzkontrinklletzter."Kontr maximale Veg-hoehe cm",
	views.v_tpop_anzkontrinklletzter."Kontr mittlere Veg-hoehe cm",
	views.v_tpop_anzkontrinklletzter."Kontr Gefaehrdung",
	views.v_tpop_anzkontrinklletzter."Kontrolle zuletzt geaendert",
	views.v_tpop_anzkontrinklletzter."Kontrolle zuletzt geaendert von",
	views.v_tpop_anzkontrinklletzter."Anzahlen",
	views.v_tpop_anzkontrinklletzter."Zaehleinheiten",
	views.v_tpop_anzkontrinklletzter."Methoden",
	views.v_tpopber_mitletzterid."AnzTPopBer",
	views.v_tpopber_mitletzterid."TPopBerId",
	views.v_tpopber_mitletzterid."TPopBer Jahr",
	views.v_tpopber_mitletzterid."TPopBer Entwicklung",
	views.v_tpopber_mitletzterid."TPopBer Bemerkungen",
	views.v_tpopber_mitletzterid."TPopBer MutWann",
	views.v_tpopber_mitletzterid."TPopBer MutWer"
FROM
	views.v_tpop_anzkontrinklletzter
  LEFT JOIN
    views.v_tpopber_mitletzterid
    ON views.v_tpop_anzkontrinklletzter."TPop ID" = views.v_tpopber_mitletzterid."TPopId";